In [15]:
#question01
import numpy as np
x=np.array([[1,3],[5,4],[6,5],[7,8]])
y=x.tolist()
print(y)

[[1, 3], [5, 4], [6, 5], [7, 8]]


In [18]:
#question02
import numpy as np
a=np.array([25,45,69,47,36,14,25,74,85])
x=a.reshape(3,3)
print(x)
y=np.trace(x)
print('the result is :')
print(y)

[[25 45 69]
 [47 36 14]
 [25 74 85]]
the result is :
146


In [39]:
#question03
import numpy as np
b = np.array([[0, 30, 40], [20, 60, 50]])
print("the array: ")
print(b)
print("Values bigger than 20 =", x[x>20])

the array: 
[[ 0 30 40]
 [20 60 50]]
Values bigger than 20 = [30 40 60 50]


In [43]:
#question04
import numpy as np
A = np.array([[5,4],[2,3],[4,7]])
B = np.array([[6,7],[4,7],[7,8]])
C = np.add(a,b)
print(C)

[[11 11]
 [ 6 10]
 [11 15]]


In [48]:
#question05
import numpy as np
A = np.array ([[3,8],[14,25],[2,12],[30,4]])
print(A)
N = np.mean(A)

print('the result :' ,N)

[[ 3  8]
 [14 25]
 [ 2 12]
 [30  4]]
the result : 12.25
